site_name: Sioux's Site
site_author: Sioux
site_description: Sioux's Private Site
copyright: Copyright &copy; 2023 - 2024 Sioux
repo_url: https://github.com/maxisioux/maxisioux.github.io
repo_name: maxisioux/maxisioux.github.io

nav:
- Home: index.md
- Projects:
    - All: projects/index.md
    - Demo-project1:
        - Getting started: projects/demo/getting-started.md
        - Setup: projects/demo/setup.md
    - Demo-project2:
        - Getting started: projects/demo/getting-started.md
- Notes:
    - All: notes/index.md
    - Markdown:
      - Start: notes/markdown/started.md
    - Python:
      - Getting started: notes/python/start.md
      - Alembic:
        - notes/python/alembic/alembic.md
      - Sqlalchemy:
        - notes/python/sqlalchemy/sqlalchemy-1.x.md
    - C++:
        - Getting started: notes/cpp/start.md
- About:
    - About: about/about.md
    - Release Notes: about/release-notes.md
    - License: about/license.md

theme:
  name: material
  custom_dir: docs/templates
  logo: assets/logo.png # 左上角主页logo
  favicon: assets/logo.png # 标签图标
  icon:
    repo: fontawesome/brands/github # 右上角repologo
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.follow

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

extra_css:
  - 'css/custom.css'
  - 'css/reference.css'
  - 'css/terminal.css'
  - 'css/tweaks.css'
extra_javascript:
  - 'js/feedback.js'
  - 'js/fluff.js'

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - callouts:
      strip_period: false
  - footnotes
  - md_in_html
  - meta
  - pymdownx.blocks.admonition
  - pymdownx.blocks.html
  - pymdownx.blocks.tab
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.inlinehilite:
      style_plain_text: python
  - pymdownx.snippets:
      check_paths: true
      base_path: [!relative $config_dir]
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "¤"

plugins:
  - search
  - markdown-exec
  - mkdocstrings:
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          - https://installer.readthedocs.io/en/stable/objects.inv  # demonstration purpose in the docs
          - https://mkdocstrings.github.io/autorefs/objects.inv
          - https://www.mkdocs.org/objects.inv
          - https://python-markdown.github.io/objects.inv
          paths: [.]
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            filters: ["!^_"]
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
  - redirects:
      redirect_maps:
        # mkdocstrings
        mkdocstrings.md: https://mkdocstrings.github.io/
        mkdocstrings/usage.md: https://mkdocstrings.github.io/usage/
        # pytkdocs
        pytkdocs.md: https://mkdocstrings.github.io/pytkdocs/
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/maxisioux